module.exports = {
  '/article/create': {is_admin: true},
  '/article/list': {is_admin: false},
  '/article/delete': {is_admin: true},
  '/article/detail': {is_admin: false},
  '/article/update': {is_admin: true},
  '/category/all': {is_admin: false},
  '/category/list': {is_admin: false},
  '/category/create': {is_admin: true},
  '/category/delete': {is_admin: true},
  '/category/update': {is_admin: true},
  '/tag/all': {is_admin: false},
  '/tag/list': {is_admin: false},
  '/tag/create': {is_admin: true},
  '/tag/delete': {is_admin: true},
  '/tag/update': {is_admin: true},
  '/upload': {is_admin: true},
  '/user/delete': {is_admin: true},
  '/user/register': {is_admin: false, userType: 0},
  '/user/login': {is_admin: false, userType: 0},
  '/user/status': {is_admin: true},
  '/user/update': {is_admin: true},
  '/user/list': {is_admin: false},
  '/user/detail': {is_admin: false},
  '/comment/list': {is_admin: false},
  '/comment/delete': {is_admin: true},
  '/reply/comment': {is_admin: true},
  '/collect_category/create': {is_admin: true},
  '/collect_category/delete': {is_admin: true},
  '/collect_category/update': {is_admin: true},
  '/collect_category/list': {is_admin: false},
  '/collect_category/all': {is_admin: false},
  '/collect/create': {is_admin: true},
  '/collect/list': {is_admin: false},
  '/collect/delete': {is_admin: true},
  '/collect/update': {is_admin: true},
  '/banner/create': {is_admin: true},
  '/banner/all': {is_admin: false},
  '/banner/delete': {is_admin: true},
  '/banner/update': {is_admin: true},
  // 前台接口
  '/post/list': {is_admin: false, userType: 0},
  '/post/archives': {is_admin: false, userType: 0},
  '/user/info': {is_admin: false, userType: 0},
  '/post/tags': {is_admin: false, userType: 0},
  '/new/posts': {is_admin: false, userType: 0},
  '/post/category': {is_admin: false, userType: 0},
  '/post/detail': {is_admin: false, userType: 0},
  '/tourist/login': {is_admin: false, userType: 0},
  '/make/comment': {is_admin: false, userType: 0},
  '/get/comments': {is_admin: false, userType: 0},
  '/front/collect': {is_admin: false, userType: 0},
  '/front/collect_category': {is_admin: false, userType: 0},
  '/banner/list': {is_admin: false, userType: 0},
  '/make/message': {is_admin: false, userType: 0},
  '/get/messages': {is_admin: false, userType: 0}
}